Documentation:
  Enabled: false
Metrics/LineLength:
  Max: 100
Style/DotPosition:
  EnforcedStyle: leading
Style/AndOr:
  EnforcedStyle: conditionals
Style/Not:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
